# Generated by Django 3.1.4 on 2022-03-17 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='api_key',
            name='last_called',
            field=models.DateField(auto_now_add=True),
        ),
    ]
